Language: python
python:
- '3.6'
install:
- pip install --user ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: 042a071ee7fe58c663acd32c7c5b7c1ee852d8c5
  - secure: d2af1bb7094e9aaa4a4ad96e7b17d682e8cbc1c7
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_8d879a3c5c12_key -iv $encrypted_8d879a3c5c12_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
